### ISSUE TITLE
Please conform the repository tag name to semver.

### ISSUE THREAD

**Issue by gyohk** [u-kudox/BitmapData_for_EaselJS#1]
When using this library via bower, it will be more convenient.
e.g. 「release_v1.1.1」 -> 「v1.1.1」 or 「1.1.1」.

**Comment by u-kudox** [comment]
Thank you for letting me know.
I got it.
I changed tag names  in the form of "1.0.0".

**Comment by gyohk** [comment]
It has become possible to use the version information via bower.
Thank you.
